### ISSUE TITLE
Installing Adam Cheetah from a local ZIP file

### ISSUE THREAD

**Issue by LAStarcevich** [tmcd82070/SDraw#2]
When I try to install v. 1.0.3 from a local zip file, I get the following error:

In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'SDraw-1.03/DESCRIPTION', probable reason 'No such file or directory'

I get this error in both 32-bit and 64-bit R 3.1.1.

**Comment by tmcd82070** [comment]
Closed
