### ISSUE TITLE
vulnerability to PROJ6/GDAL3 issues

### ISSUE THREAD

**Issue by rsbivand** [tmcd82070/SDraw#30]
**sp** and **rgdal** are changing how they handle CRS. See i.e. https://www.r-spatial.org/r/2020/03/17/wkt.html. I see:

```
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Final number of levels: 3 
  
  Stratum: None 
  Current number of levels: 1 
  Final number of levels: 1 
  
  Stratum: None 
  Current number of levels: 1 
  Final number of levels: 1 
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 74 | SKIPPED: 0 | WARNINGS: 82 | FAILED: 1 ]
  1. Failure: bas.point() operates appropriately (@test-bas.point.R#19) 
  
  Error: testthat unit tests failed
  Execution halted
```

when testing with released **sp** and devel **rgdal** on PROJ7/GDAL3.

**Comment by tmcd82070** [comment]
Thank you for the reminder.  I became aware of the changes in sp and rgdal last week.  Fix is in the works.  Planned fix is conversion to `sf` with backward compatibility for `sp` objects.

**Comment by rsbivand** [comment]
Problem now is too strict use of expect_silent(), line 19 in test.bas-point.R: `expect_silent(testSamp<-bas.point(spdf,20))`. Your use presumes that you know that upstream packages and the software they use will never change.

**Comment by tmcd82070** [comment]
fixed
