### ISSUE TITLE
Inline code text not wrapping in manual

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/SDraw#9]
It looks like you're using `devtools` and `roxygen2` to generate the help docs (Nice!).  This combo doesn't appear to wrap inline code (the \code\ tag) to the next line.  Portions of the text run off the page and are unreadable in the auto-generated PDF manual for the package.  Here's one example from `hal.polygon`.

The \code\ tag as written:
![image](https://cloud.githubusercontent.com/assets/10441106/16786947/dae40f7e-4855-11e6-885b-a11c4bae5062.png)

The \code\ tag as printed:
![image](https://cloud.githubusercontent.com/assets/10441106/16786846/32729a7c-4855-11e6-9c7f-9623f3043739.png)

I'll do some sleuthing and see if I can't find a fix.

**Comment by tmcd82070** [comment]
Thank you Jason for pointing these out.  Many such instances in documentation have been fixed.
